fm_elfinder:
  instances:
    default:
      editor: ckeditor
      locale: en
      theme: smoothness
      path_prefix: "/"
      relative_path: true
      connector:
        roots:
          uploads:
            driver: LocalFileSystem
            path: uploads/image
#             url: "%app.path.image%"
            alias: "Home"
            show_hidden: false
            upload_allow: ["image/png", "image/jpg", "image/jpeg"]
            upload_deny: ["all"]
            upload_max_size: 8M
