security:
  enable_authenticator_manager: true
  # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
  password_hashers:
    Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: "auto"
    App\Entity\CmsUser:
      algorithm: auto
  # https://symfony.com/doc/current/security.html#loading-the-user-the-user-provider
  providers:
    # used to reload user from session & other features (e.g. switch_user)
    app_user_provider:
      entity:
        class: App\Entity\CmsUser
        property: username
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: true
    main:
      lazy: true
      provider: app_user_provider
      #      custom_authenticator: App\Security\LoginFormAuthenticator
      guard:
        authenticators:
          - App\Security\LoginFormAuthenticator
      logout:
        path: app_logout
        # where to redirect after logout
        # target: app_any_route

      # activate different ways to authenticate
      # https://symfony.com/doc/current/security.html#the-firewall

      # https://symfony.com/doc/current/security/impersonating_user.html
      # switch_user: true

  # Easy way to control access for large sections of your site
  # Note: Only the *first* access control that matches will be used
  access_control:
    - { path: ^/$, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN, ROLE_NEWS_ADMIN] }
    - { path: ^/admin, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/admin-log, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/main/category, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/section, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/web/config/index, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/banner, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/content/home-chart, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/map, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/about/us, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/employee, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/development/history, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/structure/index, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/feedback, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/news, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/content/chart, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/content/pdf, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/content/ckeditor, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/content/slide, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/news/type, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/currency, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/video/news, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/job/ads/index, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN,ROLE_NEWS_ADMIN] }
    - { path: ^/profile, roles: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/efconnect, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
    - { path: ^/elfinder, role: [ROLE_ADMIN, ROLE_SUPER_ADMIN] }
