parameters:
  app.path.image: "%env(IMAGE_PATH)%"
  app.path.prefix: "%env(IMAGE_PREFIX)%"
  app.path.pdf: "%env(PDF_PATH)%"
  app.path.pdf.prefix: "%env(PDF_PREFIX)%"

vich_uploader:
  db_driver: orm
  mappings:
    app_image:
      uri_prefix: "%app.path.image%"
      upload_destination: "%kernel.project_dir%/public/uploads/image"
      namer: vich_uploader.namer_uniqid
      delete_on_update: true
      delete_on_remove: false
    pdf_files:
      uri_prefix: "%app.path.pdf%"
      upload_destination: "%kernel.project_dir%/public/uploads/pdf"
      namer: vich_uploader.namer_uniqid
