#index:
#    path: /
#    controller: App\Controller\DefaultController::index
app_file:
  resource: "../src/Controller/CurrencyController.php"
  type: annotation

download_example:
  path: "/download-example"
  controller: 'App\Controller\CurrencyController::downloadExampleAction'
